/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CpIcon: typeof import('./../components/CpIcon.vue')['default']
    CpNavBar: typeof import('./../components/CpNavBar.vue')['default']
    CpPaySheet: typeof import('./../components/CpPaySheet.vue')['default']
    CpRadioBtn: typeof import('./../components/CpRadioBtn.vue')['default']
    Navibar: typeof import('./../components/navibar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./../components/tabbar.vue')['default']
    Vnavibar: typeof import('./../components/vnavibar.vue')['default']
    Vtabbar: typeof import('./../components/vtabbar.vue')['default']
  }
}
